import { Billing, Business, Hero, Navbar, FeaturedProducts, Stats } from "@/components";

import Head from "next/head";
import Image from "next/image";
import { blurCyan } from "public/assets";
import Layout from "../components/layout/Layout";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div className=" relative bg-hero  ">
					<div className=" w-full absolute h-screen   bg-gradient-to-b from-transparent to-gray-900/50 ">
						<div className=" items-center text-center xl:max-w-[80%]  mx-auto px-10 md:px-20">
							<Navbar />
						</div>
					</div>
					<Image
									alt=""
									src={blurCyan}
									width={530}
									height={530}
									decoding="async"
									data-nimg="1"
									class="absolute bottom-full top-40 right-10 -mb-56 opacity-50"
								/>
					<Hero />
				</div>
				<Business />
				<div className="bg-linear">
					<div className=" items-center p-20 flex flex-col gap-10  text-center xl:max-w-[80%]  mx-auto px-10 md:px-20">
						<div class="mx-auto grid   justify-center items-center gap-y-16 gap-x-8 px-4">
							<div class="relative z-10 md:text-center lg:text-left">
								<Image
									alt=""
									src={blurCyan}
									width={530}
									height={530}
									decoding="async"
									data-nimg="1"
									class="absolute bottom-full right-full -mr-72 -mb-56 opacity-50"
								/>
								<div class="relative">
									<p class="inline font-poppins font-semibold bg-gradient-to-r from-indigo-200 via-sky-400 to-indigo-200 bg-clip-text font-display text-5xl tracking-tight text-transparent">
										Taichi Holdings Colombia.
									</p>
									<p class="mt-3 text-2xl tracking-tight text-slate-400">
										Poseemos un amplio catalogo de productos.
									</p>
									<div class="mt-8 flex gap-4 md:justify-center lg:justify-start">
										
									</div>
								</div>
								<div class="relative lg:static xl:pl-10">
									<div class="absolute inset-x-[-50vw] -top-32 -bottom-48 [mask-image:linear-gradient(transparent,white,white)] dark:[mask-image:linear-gradient(transparent,white,transparent)] lg:left-[calc(50%+14rem)] lg:right-0 lg:-top-32 lg:-bottom-32 lg:[mask-image:none] lg:dark:[mask-image:linear-gradient(white,white,transparent)]"></div>
								</div>
							</div>
						</div>
						<Stats />
					</div>
					<FeaturedProducts />
				</div>
			</Layout>
		</>
	);
}
